import React, { useContext } from "react";
import { graphql, Link, useStaticQuery } from "gatsby";
import { LocaleContext } from "../contexts/LocaleContext";
import * as snippet from "../locales";
import { HelmetDatoCms } from "gatsby-source-datocms";
import styled from "styled-components";
import { Layout } from "../components/Layout2";
import { theme } from "../theme/theme";
import { AnimatedBox } from "../components/AnimatedBox";
import { fullMenu, prefix } from "../constants/slugs";

// TODO: Magnetic button https://codesandbox.io/s/tgowd?file=/src/components/Button.js

const Page = ({ pageContext }) => {
  const { locale } = useContext(LocaleContext);
  const text = snippet[locale];
  const { data } = pageContext;
  console.log(prefix[locale]);
  return (
    <>
      <Layout locale={pageContext.locale} transparent={false}>
        <Main>
          <div className="Hero wrap padding">
            <div className="leftLine" />
            <div className="rightLine" />
            <div className="row">
              <div className="col">
                <h1>Älykästä määrälaskentaa.</h1>
              </div>
              <div className="col">
                <p>
                  JCAD-määrälaskentaohjelmiston avulla lasket pintojen, tilojen
                  ja rakenteiden määrät helposti, laadit tarjouksen hetkessä,
                  vältät laskuvirheet ja pidät määräluettelon ajan tasalla läpi
                  projektin.
                </p>
                <div className="row">
                  <Link className="HeroLink" to={"/maaralaskentaohjelmisto"}>
                    Tutustu ohjelmistoon
                  </Link>
                  <Link className="HeroLink" to={""}>
                    Varaa demo
                  </Link>
                </div>
              </div>
            </div>
            <div class="DashLine" />
            <div className="Grid">
              {fullMenu[locale].map((i, index) => (
                <Link
                  id={`Link-${index}`}
                  className="Link"
                  to={prefix[locale] + i.slug}
                >
                  <header className="row">
                    <span>{i.title}</span>
                    <Arrow />
                  </header>
                  <AnimatedBox index={index} />
                </Link>
              ))}
            </div>
          </div>
        </Main>
      </Layout>
    </>
  );
};

export default Page;

const Main = styled.main`
  width: 100%;
  display: flex;
  flex-direction: column;
  background: ${theme.primary};
  .DashLine {
    position: absolute;
    left: 0;
    right: 0;
    bottom: 0;
    border: none;
    border-top: 1px dashed #ffffff;
    width: 100vw;
    display: none;
    @media (max-width: 1100px) {
      display: none;
    }
  }
  .Hero {
    min-height: 100vh;
    background: ${theme.primary};
    height: 100%;
    color: #fff;
    position: relative;
    padding-top: 150px;
    @media (max-width: 600px) {
      padding-top: 50px;
    }
    .wrap {
      height: 100vh;
      @media (max-width: 1500px) {
        overflow: hidden;
      }
    }
    > .row {
      @media (max-width: 1100px) {
        flex-direction: column;
      }
    }
    h1 {
      font-size: 64px;
      margin-bottom: 40px;
      font-weight: 600;
    }
    p {
      font-size: 18px;
      line-height: 1.6;
      max-width: 720px;
      margin-bottom: 20px;
    }
  }
  .HeroLink {
    font-size: 18px;
    font-weight: 600;
    opacity: 0.6;
    margin-right: 20px;
    svg {
      margin-bottom: -5px;
      height: 18px;
    }
    &:hover {
      opacity: 1;
    }
  }
  .Grid {
    margin-top: 60px;
    margin-bottom: 60px;
    display: grid;
    grid-template-columns: repeat(3, minmax(0, 1fr));
    gap: 20px;
    @media (max-width: 1000px) {
      grid-template-columns: repeat(2, minmax(0, 1fr));
    }
    @media (max-width: 700px) {
      grid-template-columns: repeat(1, minmax(0, 1fr));
    }
  }
  .Link {
    height: 240px;
    border: 1px solid #ffffff;
    padding: 30px;
    transition: 1s;
    span {
      font-size: 20px;
      font-weight: 600;
      text-transform: uppercase;
      letter-spacing: 0.7px;
    }
    header {
      justify-content: space-between;
    }
  }
  /***************************************************
 * Generated by SVG Artista on 5/26/2022, 2:28:06 PM
 * MIT license (https://opensource.org/licenses/MIT)
 * W. https://svgartista.net
 **************************************************/
  #Link-0 {
    svg.Sleep {
      display: none;
      position: absolute;
      opacity: 0.3;
    }
    svg.Animate {
      position: absolute;
      .svg-elem-1 {
        stroke-dashoffset: 294px;
        stroke-dasharray: 294px;
        transition: stroke-dashoffset 0.5s cubic-bezier(0.47, 0, 0.745, 0.715)
          0s;
      }
      .svg-elem-2 {
        stroke-dashoffset: 864px;
        stroke-dasharray: 864px;
        transition: stroke-dashoffset 0.5s cubic-bezier(0.47, 0, 0.745, 0.715)
          0.12s;
      }
      .svg-elem-3 {
        stroke-dashoffset: 83.27300194836795px;
        stroke-dasharray: 83.27300194836795px;
        transition: stroke-dashoffset 0.5s cubic-bezier(0.47, 0, 0.745, 0.715)
          0.24s;
      }
      .svg-elem-4 {
        stroke-dashoffset: 144px;
        stroke-dasharray: 144px;
        transition: stroke-dashoffset 0.5s cubic-bezier(0.47, 0, 0.745, 0.715)
          0.36s;
      }
    }
    &:hover .Animate {
      .svg-elem-1 {
        stroke-dashoffset: 0;
      }
      .svg-elem-2 {
        stroke-dashoffset: 0;
      }
      .svg-elem-3 {
        stroke-dashoffset: 0;
      }
      .svg-elem-4 {
        stroke-dashoffset: 0;
      }
    }
  }
  #Link-1 {
    svg .svg-elem-1 {
      stroke-dashoffset: 83.27300194836795px;
      stroke-dasharray: 83.27300194836795px;
      transition: stroke-dashoffset 0.3s cubic-bezier(0.47, 0, 0.745, 0.715) 0s;
    }
    svg .svg-elem-2 {
      stroke-dashoffset: 83.27300194836795px;
      stroke-dasharray: 83.27300194836795px;
      transition: stroke-dashoffset 0.3s cubic-bezier(0.47, 0, 0.745, 0.715)
        0.12s;
    }
    svg .svg-elem-3 {
      stroke-dashoffset: 261.14683640196847px;
      stroke-dasharray: 261.14683640196847px;
      transition: stroke-dashoffset 0.3s cubic-bezier(0.47, 0, 0.745, 0.715)
        0.24s;
    }
    svg .svg-elem-4 {
      stroke-dashoffset: 134.6000518798828px;
      stroke-dasharray: 134.6000518798828px;
      transition: stroke-dashoffset 0.3s cubic-bezier(0.47, 0, 0.745, 0.715)
        0.36s;
    }
    svg .svg-elem-5 {
      stroke-dashoffset: 134.59999084472656px;
      stroke-dasharray: 134.59999084472656px;
      transition: stroke-dashoffset 0.3s cubic-bezier(0.47, 0, 0.745, 0.715)
        0.48s;
    }
    &:hover {
      svg .svg-elem-1 {
        stroke-dashoffset: 0;
      }
      svg .svg-elem-2 {
        stroke-dashoffset: 0;
      }
      svg .svg-elem-3 {
        stroke-dashoffset: 0;
      }
      svg .svg-elem-4 {
        stroke-dashoffset: 0;
      }
      svg .svg-elem-5 {
        stroke-dashoffset: 0;
      }
    }
  }
  #Link-4 {
    svg .svg-elem-1 {
      stroke-dashoffset: 856px;
      stroke-dasharray: 856px;
      transition: stroke-dashoffset 0.4s cubic-bezier(0.47, 0, 0.745, 0.715) 0s,
        fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0s;
    }
    svg .svg-elem-2 {
      stroke-dashoffset: 392.60772705078125px;
      stroke-dasharray: 392.60772705078125px;
      fill: transparent;
      transition: stroke-dashoffset 0.4s cubic-bezier(0.47, 0, 0.745, 0.715)
          0.12s,
        fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0s;
    }
    svg .svg-elem-3 {
      stroke-dashoffset: 883.2762451171875px;
      stroke-dasharray: 883.2762451171875px;
      fill: transparent;
      transition: stroke-dashoffset 0.4s cubic-bezier(0.47, 0, 0.745, 0.715)
          0.24s,
        fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.1s;
    }
    svg .svg-elem-4 {
      stroke-dashoffset: 288.6121520996094px;
      stroke-dasharray: 288.6121520996094px;
      fill: transparent;
      transition: stroke-dashoffset 0.4s cubic-bezier(0.47, 0, 0.745, 0.715)
          0.36s,
        fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.2s;
    }
    svg .svg-elem-5 {
      stroke-dashoffset: 669.257080078125px;
      stroke-dasharray: 669.257080078125px;
      fill: transparent;
      transition: stroke-dashoffset 0.4s cubic-bezier(0.47, 0, 0.745, 0.715)
          0.48s,
        fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.3s;
    }
    svg .svg-elem-6 {
      stroke-dashoffset: 226.07794189453125px;
      stroke-dasharray: 226.07794189453125px;
      transition: stroke-dashoffset 0.4s cubic-bezier(0.47, 0, 0.745, 0.715)
          0.6s,
        fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.4s;
    }
    svg .svg-elem-7 {
      stroke-dashoffset: 404.1275634765625px;
      stroke-dasharray: 404.1275634765625px;
      transition: stroke-dashoffset 0.4s cubic-bezier(0.47, 0, 0.745, 0.715)
          0.72s,
        fill 0.7s cubic-bezier(0.47, 0, 0.745, 0.715) 0.5s;
    }
    &:hover {
      svg .svg-elem-1 {
        stroke-dashoffset: 0;
      }
      svg .svg-elem-2 {
        stroke-dashoffset: 0;
        fill: rgb(255, 255, 255);
      }
      svg .svg-elem-3 {
        stroke-dashoffset: 0;
        fill: rgb(255, 255, 255);
      }
      svg .svg-elem-4 {
        stroke-dashoffset: 0;
        fill: rgb(255, 255, 255);
      }
      svg .svg-elem-5 {
        stroke-dashoffset: 0;
        fill: rgb(255, 255, 255);
      }
      svg .svg-elem-6 {
        stroke-dashoffset: 0;
      }
      svg .svg-elem-7 {
        stroke-dashoffset: 0;
      }
    }
  }
`;

const Arrow = () => (
  <svg
    width="20"
    height="22"
    viewBox="0 0 20 22"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      d="M9 0L7.95306 1.04694L16.7381 9.83198L0.0848444 9.5294L0.05812 11.0095L16.8042 11.3151L7.95305 20.1663L8.99999 21.2132L19.6066 10.6066L9 0Z"
      fill="white"
    />
  </svg>
);
